spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    driver-class-name: org.h2.Driver
  batch:
    jdbc:
      initialize-schema: embedded

    job:
      name: ${job.names}
  cloud:
    aws:
      credentials:
        access-key: ${aws.access-key}
        secret-key: ${aws.secret-key}
      region:
        static: ${aws.region}
      sqs:
        enabled: true