spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  batch:
    jdbc:
      initialize-schema: always
    job:
      #      name: ${job.names:NONE}
      enabled: false
  cloud:
    aws:
      credentials:
        access-key: ${aws.access-key}
        secret-key: ${aws.secret-key}
      region:
        static: ${aws.region}
      sqs:
        enabled: true
      sns:
        enabled: true