spring:
  application:
    name: localstack
  cloud:
    aws:
      endpoint: http://localhost:4566
      region:
        static: us-east-1
      credentials:
        access-key: test
        secret-key: test


#      endpoint: localhost:4566
